\set DATABASE 'ecom'
\set USERNAME 'medusa'
\set SCHEMA_NAME 'medusa'

CREATE USER :"USERNAME" PASSWORD 'medusa';

DROP DATABASE IF EXISTS  :"DATABASE";
CREATE DATABASE :"DATABASE";
GRANT CONNECT, CREATE, TEMPORARY ON DATABASE :"DATABASE" TO :"USERNAME";
ALTER DATABASE :"DATABASE" SET search_path TO public, :"SCHEMA_NAME";

\c :"DATABASE"

DROP SCHEMA IF EXISTS public CASCADE;
DROP SCHEMA IF EXISTS :"SCHEMA_NAME" CASCADE;

\dn