import { defineObject, FieldType, RelationType, OnDeleteAction } from 'twenty-sdk/define';

import {
  DELIVERY_ADDRESS_FIELD_ID,
  DELIVERY_CARRIER_FIELD_ID,
  DELIVERY_DELIVERED_AT_FIELD_ID,
  DELIVERY_DELIVERY_ID_FIELD_ID,
  DELIVERY_ESTIMATED_DELIVERY_AT_FIELD_ID,
  DELIVERY_ORDER_FIELD_ID,
  DELIVERY_SHIPPED_AT_FIELD_ID,
  DELIVERY_STATUS_FIELD_ID,
  DELIVERY_STATUS_OPTION_IDS,
  DELIVERY_TRACKING_NUMBER_FIELD_ID,
  DELIVERY_TRACKING_URL_FIELD_ID,
  DELIVERY_UNIVERSAL_IDENTIFIER,
  DELIVERY_WAREHOUSE_CODE_FIELD_ID,
  ORDER_DELIVERY_FIELD_ID,
  ORDER_UNIVERSAL_IDENTIFIER,
} from 'src/constants/order-service-identifiers';

export default defineObject({
  universalIdentifier: DELIVERY_UNIVERSAL_IDENTIFIER,
  nameSingular: 'delivery',
  namePlural: 'deliveries',
  labelSingular: 'Delivery',
  labelPlural: 'Deliveries',
  description: 'A shipment delivering the items of an order to the customer.',
  icon: 'IconTruckDelivery',
  labelIdentifierFieldMetadataUniversalIdentifier: DELIVERY_TRACKING_NUMBER_FIELD_ID,
  fields: [
    {
      universalIdentifier: DELIVERY_TRACKING_NUMBER_FIELD_ID,
      name: 'trackingNumber',
      label: 'Tracking Number',
      type: FieldType.TEXT,
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: DELIVERY_CARRIER_FIELD_ID,
      name: 'carrier',
      label: 'Carrier',
      type: FieldType.TEXT,
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: DELIVERY_STATUS_FIELD_ID,
      name: 'status',
      label: 'Status',
      type: FieldType.SELECT,
      defaultValue: "'PENDING'",
      options: [
        { id: DELIVERY_STATUS_OPTION_IDS.PENDING, value: 'PENDING', label: 'Pending', color: 'gray', position: 0 },
        { id: DELIVERY_STATUS_OPTION_IDS.SHIPPED, value: 'SHIPPED', label: 'Shipped', color: 'yellow', position: 1 },
        { id: DELIVERY_STATUS_OPTION_IDS.DELIVERED, value: 'DELIVERED', label: 'Delivered', color: 'green', position: 2 },
        { id: DELIVERY_STATUS_OPTION_IDS.FAILED, value: 'FAILED', label: 'Failed', color: 'red', position: 3 },
        { id: DELIVERY_STATUS_OPTION_IDS.RETURNED, value: 'RETURNED', label: 'Returned', color: 'orange', position: 4 },
      ],
    },
    {
      universalIdentifier: DELIVERY_SHIPPED_AT_FIELD_ID,
      name: 'shippedAt',
      label: 'Shipped At',
      type: FieldType.DATE_TIME,
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: DELIVERY_DELIVERED_AT_FIELD_ID,
      name: 'deliveredAt',
      label: 'Delivered At',
      type: FieldType.DATE_TIME,
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: DELIVERY_ADDRESS_FIELD_ID,
      name: 'address1',
      label: 'Delivery Address',
      type: FieldType.ADDRESS,
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: DELIVERY_DELIVERY_ID_FIELD_ID,
      name: 'deliveryId',
      label: 'Delivery ID',
      description: 'External delivery id from the source system, used as the upsert key (specs-2.md §2.5).',
      type: FieldType.TEXT,
      isUnique: true,
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: DELIVERY_TRACKING_URL_FIELD_ID,
      name: 'trackingUrl',
      label: 'Tracking URL',
      type: FieldType.TEXT,
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: DELIVERY_WAREHOUSE_CODE_FIELD_ID,
      name: 'warehouseCode',
      label: 'Warehouse Code',
      type: FieldType.TEXT,
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: DELIVERY_ESTIMATED_DELIVERY_AT_FIELD_ID,
      name: 'estimatedDeliveryAt',
      label: 'Estimated Delivery At',
      type: FieldType.DATE_TIME,
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: DELIVERY_ORDER_FIELD_ID,
      name: 'order',
      label: 'Order',
      type: FieldType.RELATION,
      relationTargetObjectMetadataUniversalIdentifier: ORDER_UNIVERSAL_IDENTIFIER,
      relationTargetFieldMetadataUniversalIdentifier: ORDER_DELIVERY_FIELD_ID,
      universalSettings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: OnDeleteAction.CASCADE,
        joinColumnName: 'orderId',
      },
    },
  ],
});
