import { defineObject, FieldType, RelationType, STANDARD_OBJECT } from 'twenty-sdk/define';


import {
  DELIVERY_ORDER_FIELD_ID,
  DELIVERY_UNIVERSAL_IDENTIFIER,
  ORDER_CANCEL_REASON_FIELD_ID,
  ORDER_CANCELLED_AT_FIELD_ID,
  ORDER_CUSTOMER_FIELD_ID,
  ORDER_DELIVERY_FIELD_ID,
  ORDER_ITEM_ORDER_FIELD_ID,
  ORDER_ITEM_UNIVERSAL_IDENTIFIER,
  ORDER_ORDER_ITEMS_FIELD_ID,
  ORDER_ORDER_NUMBER_FIELD_ID,
  ORDER_PARTIALLY_REFUNDED_AMOUNT_FIELD_ID,
  ORDER_PLACED_AT_FIELD_ID,
  ORDER_REFUNDED_AMOUNT_FIELD_ID,
  ORDER_REFUNDED_AT_FIELD_ID,
  ORDER_SOURCE_FIELD_ID,
  ORDER_SOURCE_OPTION_IDS,
  ORDER_STATUS_FIELD_ID,
  ORDER_STATUS_OPTION_IDS,
  ORDER_TOTAL_AMOUNT_FIELD_ID,
  ORDER_UNIVERSAL_IDENTIFIER,
  PERSON_ORDERS_FIELD_ID,
} from 'src/constants/order-service-identifiers';

export default defineObject({
  universalIdentifier: ORDER_UNIVERSAL_IDENTIFIER,
  nameSingular: 'order',
  namePlural: 'orders',
  labelSingular: 'Order',
  labelPlural: 'Orders',
  description: 'A customer order placed through the Order Service.',
  icon: 'IconShoppingCart',
  labelIdentifierFieldMetadataUniversalIdentifier: ORDER_ORDER_NUMBER_FIELD_ID,
  fields: [
    {
      universalIdentifier: ORDER_ORDER_NUMBER_FIELD_ID,
      name: 'orderNumber',
      label: 'Order Number',
      type: FieldType.TEXT,
      isUnique: true,
    },
    {
      universalIdentifier: ORDER_STATUS_FIELD_ID,
      name: 'status',
      label: 'Status',
      type: FieldType.SELECT,
      defaultValue: "'CREATED'",
      options: [
        { id: ORDER_STATUS_OPTION_IDS.CREATED, value: 'CREATED', label: 'Created', color: 'gray', position: 0 },
        { id: ORDER_STATUS_OPTION_IDS.PAID, value: 'PAID', label: 'Paid', color: 'blue', position: 1 },
        { id: ORDER_STATUS_OPTION_IDS.CANCELLED, value: 'CANCELLED', label: 'Cancelled', color: 'red', position: 2 },
        { id: ORDER_STATUS_OPTION_IDS.REFUNDED, value: 'REFUNDED', label: 'Refunded', color: 'orange', position: 3 },
      ],
    },
    {
      universalIdentifier: ORDER_TOTAL_AMOUNT_FIELD_ID,
      name: 'totalAmount',
      label: 'Total Amount',
      type: FieldType.CURRENCY,
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: ORDER_PLACED_AT_FIELD_ID,
      name: 'placedAt',
      label: 'Placed At',
      type: FieldType.DATE_TIME,
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: ORDER_SOURCE_FIELD_ID,
      name: 'source',
      label: 'Source',
      type: FieldType.SELECT,
      isNullable: true,
      defaultValue: null,
      options: [
        { id: ORDER_SOURCE_OPTION_IDS.WEB, value: 'WEB', label: 'Web', color: 'blue', position: 0 },
        { id: ORDER_SOURCE_OPTION_IDS.MOBILE, value: 'MOBILE', label: 'Mobile', color: 'purple', position: 1 },
        { id: ORDER_SOURCE_OPTION_IDS.POS, value: 'POS', label: 'POS', color: 'green', position: 2 },
        { id: ORDER_SOURCE_OPTION_IDS.API, value: 'API', label: 'API', color: 'gray', position: 3 },
      ],
    },
    {
      universalIdentifier: ORDER_CANCELLED_AT_FIELD_ID,
      name: 'cancelledAt',
      label: 'Cancelled At',
      type: FieldType.DATE_TIME,
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: ORDER_CANCEL_REASON_FIELD_ID,
      name: 'cancelReason',
      label: 'Cancel Reason',
      type: FieldType.TEXT,
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: ORDER_REFUNDED_AMOUNT_FIELD_ID,
      name: 'refundedAmount',
      label: 'Refunded Amount',
      type: FieldType.CURRENCY,
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: ORDER_REFUNDED_AT_FIELD_ID,
      name: 'refundedAt',
      label: 'Refunded At',
      type: FieldType.DATE_TIME,
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: ORDER_PARTIALLY_REFUNDED_AMOUNT_FIELD_ID,
      name: 'partiallyRefundedAmount',
      label: 'Partially Refunded Amount',
      type: FieldType.CURRENCY,
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: ORDER_ORDER_ITEMS_FIELD_ID,
      name: 'orderItems',
      label: 'Order Items',
      type: FieldType.RELATION,
      relationTargetObjectMetadataUniversalIdentifier: ORDER_ITEM_UNIVERSAL_IDENTIFIER,
      relationTargetFieldMetadataUniversalIdentifier: ORDER_ITEM_ORDER_FIELD_ID,
      universalSettings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    {
      universalIdentifier: ORDER_DELIVERY_FIELD_ID,
      name: 'deliveries',
      label: 'Deliveries',
      type: FieldType.RELATION,
      relationTargetObjectMetadataUniversalIdentifier: DELIVERY_UNIVERSAL_IDENTIFIER,
      relationTargetFieldMetadataUniversalIdentifier: DELIVERY_ORDER_FIELD_ID,
      universalSettings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    {
      universalIdentifier: ORDER_CUSTOMER_FIELD_ID,
      name: 'customer',
      label: 'Customer',
      type: FieldType.RELATION,
      relationTargetObjectMetadataUniversalIdentifier: STANDARD_OBJECT.person.universalIdentifier,
      relationTargetFieldMetadataUniversalIdentifier: PERSON_ORDERS_FIELD_ID,
      universalSettings: {
        relationType: RelationType.MANY_TO_ONE,
        joinColumnName: 'customerId',
      },
    },
  ],
});
