import { defineObject, FieldType } from 'twenty-sdk/define';

import {
  SYNC_LOG_ENTITY_TYPE_OPTION_IDS,
  SYNC_LOG_ENTRY_ATTEMPTS_FIELD_ID,
  SYNC_LOG_ENTRY_ENTITY_TYPE_FIELD_ID,
  SYNC_LOG_ENTRY_EVENT_ID_FIELD_ID,
  SYNC_LOG_ENTRY_EVENT_TYPE_FIELD_ID,
  SYNC_LOG_ENTRY_EXTERNAL_KEY_FIELD_ID,
  SYNC_LOG_ENTRY_LAST_ERROR_FIELD_ID,
  SYNC_LOG_ENTRY_STATUS_FIELD_ID,
  SYNC_LOG_ENTRY_TWENTY_ID_FIELD_ID,
  SYNC_LOG_ENTRY_UNIVERSAL_IDENTIFIER,
  SYNC_LOG_STATUS_OPTION_IDS,
} from 'src/constants/order-service-identifiers';

export default defineObject({
  universalIdentifier: SYNC_LOG_ENTRY_UNIVERSAL_IDENTIFIER,
  nameSingular: 'syncLogEntry',
  namePlural: 'syncLogEntries',
  labelSingular: 'Sync Log Entry',
  labelPlural: 'Sync Log Entries',
  description: 'Idempotency ledger for the CRM Integration Service (specs-2.md §4).',
  icon: 'IconRefresh',
  labelIdentifierFieldMetadataUniversalIdentifier: SYNC_LOG_ENTRY_EVENT_ID_FIELD_ID,
  fields: [
    {
      universalIdentifier: SYNC_LOG_ENTRY_EVENT_ID_FIELD_ID,
      name: 'eventId',
      label: 'Event ID',
      description: 'Idempotency key from the event envelope, e.g. evt_01J...ULID.',
      type: FieldType.TEXT,
      isUnique: true,
    },
    {
      universalIdentifier: SYNC_LOG_ENTRY_EVENT_TYPE_FIELD_ID,
      name: 'eventType',
      label: 'Event Type',
      description: 'e.g. order.created, delivery.status_updated.',
      type: FieldType.TEXT,
    },
    {
      universalIdentifier: SYNC_LOG_ENTRY_ENTITY_TYPE_FIELD_ID,
      name: 'entityType',
      label: 'Entity Type',
      type: FieldType.SELECT,
      defaultValue: "'ORDER'",
      options: [
        { id: SYNC_LOG_ENTITY_TYPE_OPTION_IDS.PERSON, value: 'PERSON', label: 'Person', color: 'blue', position: 0 },
        { id: SYNC_LOG_ENTITY_TYPE_OPTION_IDS.ORDER, value: 'ORDER', label: 'Order', color: 'green', position: 1 },
        { id: SYNC_LOG_ENTITY_TYPE_OPTION_IDS.ORDER_ITEM, value: 'ORDER_ITEM', label: 'Order Item', color: 'turquoise', position: 2 },
        { id: SYNC_LOG_ENTITY_TYPE_OPTION_IDS.DELIVERY, value: 'DELIVERY', label: 'Delivery', color: 'purple', position: 3 },
      ],
    },
    {
      universalIdentifier: SYNC_LOG_ENTRY_EXTERNAL_KEY_FIELD_ID,
      name: 'externalKey',
      label: 'External Key',
      description: 'externalCustomerId | orderNumber | deliveryId, depending on entityType.',
      type: FieldType.TEXT,
    },
    {
      universalIdentifier: SYNC_LOG_ENTRY_TWENTY_ID_FIELD_ID,
      name: 'twentyId',
      label: 'Twenty ID',
      description: 'Null until the first successful write to Twenty.',
      type: FieldType.UUID,
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: SYNC_LOG_ENTRY_STATUS_FIELD_ID,
      name: 'status',
      label: 'Status',
      type: FieldType.SELECT,
      defaultValue: "'PENDING'",
      options: [
        { id: SYNC_LOG_STATUS_OPTION_IDS.PENDING, value: 'PENDING', label: 'Pending', color: 'gray', position: 0 },
        { id: SYNC_LOG_STATUS_OPTION_IDS.SUCCESS, value: 'SUCCESS', label: 'Success', color: 'green', position: 1 },
        { id: SYNC_LOG_STATUS_OPTION_IDS.PARTIAL, value: 'PARTIAL', label: 'Partial', color: 'yellow', position: 2 },
        { id: SYNC_LOG_STATUS_OPTION_IDS.FAILED, value: 'FAILED', label: 'Failed', color: 'red', position: 3 },
      ],
    },
    {
      universalIdentifier: SYNC_LOG_ENTRY_ATTEMPTS_FIELD_ID,
      name: 'attempts',
      label: 'Attempts',
      type: FieldType.NUMBER,
      defaultValue: 0,
    },
    {
      universalIdentifier: SYNC_LOG_ENTRY_LAST_ERROR_FIELD_ID,
      name: 'lastError',
      label: 'Last Error',
      type: FieldType.TEXT,
      isNullable: true,
      defaultValue: null,
    },
  ],
});
